const CREATE_CARD = 'cards/CREATE_CARD'
const DELETE_CARD = 'cards/DELETE_CARD'
const CHANGE_TYPE = 'cards/CHANGE_TYPE'
const UPDATE_QUESTION = 'cards/UPDATE_QUESTION'
const ADD_SUB_INPUT = 'cards/ADD_SUB_INPUT'

export default {
  CREATE_CARD,
  DELETE_CARD,
  CHANGE_TYPE,
  UPDATE_QUESTION,
  ADD_SUB_INPUT
}